name: Update Performance Metrics

# Triggers for the workflow
on:
  # Run when manually triggered using GitHub's UI
  workflow_dispatch:
  
  # Run on pushes to main branch that modify C files or scripts
  push:
    branches: [ main ]
    paths:
      - '**.c'
      - '**.h'
      - 'test_*.sh'
      - 'find_optimal_blocksize.sh'
  
  # Run on pull requests to main branch that modify C files or scripts
  pull_request:
    branches: [ main ]
    paths:
      - '**.c'
      - '**.h'
      - 'test_*.sh'
      - 'find_optimal_blocksize.sh'
  
  # Run once a week (Sunday at 00:00 UTC)
  schedule:
    - cron: '0 0 * * 0'

jobs:
  update-metrics:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential bc
    
    - name: Ensure scripts are executable
      run: |
        chmod +x find_optimal_blocksize.sh
        chmod +x test_ranges.sh
    
    - name: Create build directory
      run: mkdir -p build
    
    - name: Find optimal block size
      run: ./find_optimal_blocksize.sh
    
    - name: Run performance tests
      run: ./test_ranges.sh
      
    - name: Create summary of system information
      run: |
        echo "## Test Environment" > system_info.md
        echo "- Date: $(date)" >> system_info.md
        echo "- CPU Model: $(grep 'model name' /proc/cpuinfo | head -n1 | cut -d':' -f2 | xargs)" >> system_info.md
        echo "- CPU Cores: $(grep -c processor /proc/cpuinfo)" >> system_info.md
        echo "- Memory: $(free -h | awk '/^Mem:/ {print $2}')" >> system_info.md
        echo "- OS: $(lsb_release -ds)" >> system_info.md
        echo "- Kernel: $(uname -r)" >> system_info.md
        echo "- Optimal block size: $(cat optimal_block_size.txt) bytes" >> system_info.md
    
    - name: Update README with system info
      run: |
        # Extract the performance table from README.md
        sed -n '/^## Performance Summary/,/^$/p' README.md > perf_table.md
        
        # Combine system info with performance table
        cat system_info.md perf_table.md > new_readme.md
        
        # Add implementation notes from old README
        sed -n '/^## Implementation Notes/,$p' README.md >> new_readme.md
        
        # Replace README with new content
        mv new_readme.md README.md
        
        # Clean up temporary files
        rm -f perf_table.md system_info.md
        
    - name: Commit changes
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'
        
        # Check if there are changes to commit
        if [ -n "$(git status --porcelain)" ]; then
          git add README.md range_results.txt block_size_results.txt optimal_block_size.txt
          git commit -m "Update performance metrics [skip ci]"
          git push
        else
          echo "No changes to commit"
        fi